"""updated quiz models

Revision ID: 7a95ce5a356d
Revises: 20b78788a743
Create Date: 2025-04-20 04:06:41.458029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7a95ce5a356d'
down_revision: Union[str, None] = '20b78788a743'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quiz_questions', sa.Column('options', sa.JSON(), nullable=False))
    op.add_column('quiz_questions', sa.Column('is_ai_generated', sa.Boolean(), nullable=True))
    op.alter_column('quiz_questions', 'question',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=sa.Text(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('quiz_questions', 'question',
               existing_type=sa.Text(),
               type_=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.drop_column('quiz_questions', 'is_ai_generated')
    op.drop_column('quiz_questions', 'options')
    # ### end Alembic commands ###
